@Restaurants.API_HostAddress = https://localhost:7267

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/example?max=100
Accept: application/json
Guid:{{$guid}}
LocalDate:{{$datetime iso8601}}
Random-int:{{$randomInt}}

###





@count=0
POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?count=2
Content-Type: application/json

{
  "min":10,
  "max":50
}

###
