@Restaurants.API_HostAddress = https://localhost:7267
@token=CfDJ8BLcefdNlD1BkxK1NIeiig2iAbqyhoIGxNgV8TBGWrZmxsl-PQfNOvA7CKWrXY0pVTiO-7-HXsHOSJaOY5U0Wz5q5byOMXIKRsoXH45hthSSI-_M-sneDRt_7ICEWTTN9eu86JcjYxJLzQZ02RKD8UbtSRln7ATSgX5E4ocVzk2fLlysuWMvnwnzy2bcBAgGi6zNuYWejpwhMS2aFJJoD9ZDfXfNpSRVFgyY7_KDDrRloUzAV3w9OoNet8RhL0dDDXJ2pmnE_FNsVsynWA8yzz3KtjPhSswjyxN23Gv0e3sHn4F9m7nTGF7oAtdotxAiiGCCfCP6horZTarBGgUfvjMvzuJtpa28pub-SlQMisT03qCy2ZeCN-4bcflTYGzVdyw3nxDTYoip_TpkV3FBRIPLZYtjmgKfzthiYxhGjvtEMOZswS_7sfNo5LSYi5jWY4Yva9OB0LtEstUaNCFOXCPC7Y_fJzaD3Aeu3C5h8JoM9Ex4FnHVXs0KanZ4WUXElr02Ou-fVTwxyPFMwilugURl8I6BuEc4SnlYCAdOE50TjqG3SZ36N5nY21t35BxZmTJKwK_ORV5JpykB_o-zbdS55c0RDjbx7Uqa0Q0zfMJizLunZ5XymKeGy_Z5TapGHYqF0nlBqu2V9k-gNiya7lPsKNnU4KHD8qVsI6xVnZweIKJmdEMTOFq8SL6Dch4fHdxNwRj95V83mH-IGCVNiMUfzQJt2YqBxry7Havve_AK4kZSfgGtWknHCbxzaw4m5Rw-creP13eIGWzrbkNdRhzPB_vFj6Irpe1eYFHSu3AtFwL6icrBQLMw-g4J9tP8S27G2urIFFJRGFx1p-oStU2y52o_74ahFj0rXjT1vD9wyzpRs9xkqzxSnAOr-jxFUA

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/example?max=100
Accept: application/json
Guid:{{$guid}}
LocalDate:{{$datetime iso8601}}
Random-int:{{$randomInt}}

###

@count=0
POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?count=2
Content-Type: application/json

{
  "min":10,
  "max":50
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/11
Authorization : Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
   "Name": "Chinees Tests33123",
   "Description": "A cozy restaurant serving a variety ggg of delicious dishes.",
   "Category": "Indian",
   "HasDelivery": true,
   "ContactEmail": "Chinees@test.com",
   "ContactNumber": "555-123473",
   "City": "Bilimora",
   "Street": "143 Main Streetee",
   "PostalCode": "10-143"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
   "Name": "Test patch8",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name":"Pasta33 Carbonara33",
  "Description":"Classic Italian pasta233 dish with creamy sauce and pancetta.",
  "Price":10.99,
  "KiloCalories":200
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Authorization : Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantsId}/dishes/{dishId}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "Polish",
  "DateOfBirth": "1990-05-20"
}

###

# @restaurantsId=1
# GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantsId}}/dishes
# Authorization: Bearer {{token}}

# ###
