@Restaurants.API_HostAddress = https://localhost:7267
@token=CfDJ8BLcefdNlD1BkxK1NIeiig0HzEiLtW21Dg359AJikpeR7lUPNVJ0fmIV_Y8QvQjGeLrQSoPbjMg7Ac2J7KKEhrxsqqbHAJMZQ-VqoyoUwzo4dN5QnZt_azhGDWUGiCKYUNeUhvenzT7iYbLYdomkv6EXE9x6KYEDD9tIOwcuxAS3a92EPKeJP2IVDXhjcIj_aSfmpGS1uZ0TkC5xPIsbpqvv1weSc4p4fsiN4HoiDHg4n5gr8UeriY6ZwiByEdbeCHNxtnh2dqLfksa_07JXyLfL0Nv6jAmwlpC2WiyJHtlh3otE7Yf_WriD5gDyoFhYSjSXAAsdU1HAJCaPfy6ll7ZnsuB73bLO569UX9C8bNO8L_rLlTCV4_Qi9iMXb0GllRx2ZuIl3C4ZMLH-YybzSGGjhiznIer67Niwp1-Tya9ditslnD6HcNPY6ZoLP4QotHY4I-aLPmwKHtb72ANTaKC09H1OC59JcIbR_d3mxxhnRTMy4I3-f1-4Cp5kU0D30Fdvmhg9sePyBm-zb_tcd7gR4-kVr44ubzWFyxsZqTQzpVMZ7njHKJwtkfh3MktbcYG54JweD_sNbkHYKlp59tNUfJ0tgViDL6-jz5Iak_wlxMEkTbpzIUpCaCTgRLy4xC8CSliIyT8iBttZAUqiMlVK4LzlCHj3BU-kKffxfrmh8Z-DJwBtSPWcRS8KNk7Wr2gtYDto1YFGSBSxU8Y4An8cTqRTcNJ4YRmp9PGjh6qT5cyBMydoTYqaF5DTQz5AIeeNk9roMilolQ6bA8foh6oZGp8Ll1pW4x8sFBUhHaPktz1ls7Oj58yFTVrhk8zL5cPFuGxrqzRVPm4hUpRSxIimsJoU3dvFOAuqe6U-_xaKzburDGIxY7cv170CwoiHvA

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/example?max=100
Accept: application/json
Guid:{{$guid}}
LocalDate:{{$datetime iso8601}}
Random-int:{{$randomInt}}

###

@count=0
POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?count=2
Content-Type: application/json

{
  "min":10,
  "max":50
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/11
Authorization : Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
   "Name": "Chinees Tests33123",
   "Description": "A cozy restaurant serving a variety ggg of delicious dishes.",
   "Category": "Indian",
   "HasDelivery": true,
   "ContactEmail": "Chinees@test.com",
   "ContactNumber": "555-123473",
   "City": "Bilimora",
   "Street": "143 Main Streetee",
   "PostalCode": "10-143"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/11
Authorization : Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/11
Content-Type: application/json
Authorization : Bearer {{token}}

{
   "Name": "updated Test patch111111",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name":"Pasta33 Carbonara33",
  "Description":"Classic Italian pasta233 dish with creamy sauce and pancetta.",
  "Price":10.99,
  "KiloCalories":200
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Authorization : Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantsId}/dishes/{dishId}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "Polish",
  "DateOfBirth": "1990-05-20"
}

###

# @restaurantsId=1
# GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantsId}}/dishes
# Authorization: Bearer {{token}}

# ###
